language: cpp
before_script:
- sudo apt-get install libboost-test-dev -y
- echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq
script:
- mkdir build
- cd build
- cmake ..
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
  on:
    all_branches: true
  provider: script
  skip_cleanup: true
  script:
  - curl -T otus-cpp-hw2-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -udendasus:$BINTRAY_API_KEY "https://api.bintray.com/content/dendasus/OTUS-CPP_homeworks/HomeWorks/$TRAVIS_BUILD_NUMBER/otus-cpp-hw2-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
